# Runs the backend service using it's image name pizzabackend, generated by the script build-docker-image.sh (must run before this)
docker run -it --rm -p 5200:80 --name pizzabackendcontainer pizzabackend
